import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  ColorSchemeScript,
  MantineColorScheme,
  MantineProvider,
} from "@mantine/core";
import { Navbar } from "@/features/app/Navbar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Movie List",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/FantasyCatLogo.png",
      rel: "icon",
      type: "image/x-icon",
    },
  ],
};

export type LayoutProps = {
  children: React.ReactNode;
};

export type Theme = "light" | "dark";

export default function RootLayout({ children }: Readonly<LayoutProps>) {
  const cookieStore = cookies();
  const themeCookie = cookieStore.get("theme");
  let theme: MantineColorScheme = "dark";
  if (!themeCookie) {
    // cookieStore.set("theme", "dark");
  }
  // theme = themeCookie!.value as MantineColorScheme;
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <MantineProvider defaultColorScheme={theme}>
          <Navbar />
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
